---
- name: Authorized Keys
  hosts: all
  become: yes
  gather_facts: true
  vars:
    user_name: test_user
  tasks:
    - name: user
      user:
        name: "{{user_name}}"
        state: present
    - name: facts
      authorized_key:
        user: "{{user_name}}"
        state: present
        key: "{{lookup('file','/home/ec2-user/.ssh/id_rsa.pub')}}"
        exclusive: true
