---
- name: Installing jboss
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    - packages:
        - java-11-openjdk-devel
        - wget
        - curl
    - wildfly_release_url:
#          - "https://api.github.com/repos/wildfly/wildfly/releases/latest"
          - "https://github.com/wildfly/wildfly/releases/download/${WILDFLY_RELEASE}/wildfly-${WILDFLY_RELEASE}.tar.gz"
  tasks:
    - name: Downloading packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
    - name: wildfly url
      get_url:
        url: "{{ wildfly_release_url }}"
        dest: ./wildfly/releases/
#        with_items: "{{ wildfly_release_url }}"
    - name: unarchiving tar
      ansible.builtin.unarchive:
        src: wildfly-${WILDFLY_RELEASE}.tar.gz
        dest: ./opt/wildfly

