---
- name: Installing jboss
  hosts: all
  become: yes
  gather_facts: true
  vars:
    - packages:
        - java-11-openjdk-devel
  tasks:
    - name: Downloading packages
      yum:
        loop: "{{ packages }}"
        state: present
