---
- name: Installing jboss
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    - packages:
        - java-11-openjdk-devel
        - wget
        - curl
    - shell_commands:
#        - "semanage fcontext  -a -t bin_t  '/opt/wildfly/bin(/.*)?'"
        - "restorecon -Rv /opt/wildfly/bin/"
#    - wildfly_release_url:
#        - ansible-galaxy collection install middleware_automation.wildfly
#        - "https://github.com/wildfly/wildfly/releases/download/27.0.1.Final/wildfly-27.0.1.Final.tar.gz"
#          - "https://api.github.com/repos/wildfly/wildfly/releases/latest"
  tasks:
    - name: Downloading packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
    - name: wildfly url
      get_url:
        url: "https://github.com/wildfly/wildfly/releases/download/27.0.1.Final/wildfly-27.0.1.Final.tar.gz"
        dest: /home/centos
        mode: '0755'
#        with_items: "{{ wildfly_release_url }}"
    - name: unarchiving tar
      ansible.builtin.unarchive:
        src: "/home/centos/wildfly-27.0.1.Final.tar.gz"
        dest: /opt/wildfly
        remote_src: yes
    - name: adding a system group
      group:
        name: wildfly
        state: present
        system: true
    - name: adding a system user
      user:
        name: wildfly
        group: wildfly
        state: present
        system: true
    - name: creating directory
      file:
        path: /etc/wildfly
        state: directory
        mode: "0755"
    - name: copying configuration file
      copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf
        dest: /etc/wildfly/
        owner: wildfly
        group: wildfly
        mode: "0644"
    - name: copying service file
      copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service
        dest: /etc/systemd/system/
        owner: wildfly
        group: wildfly
        mode: "0644"
    - name: copying launch file
      copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/launch.sh
        dest: /opt/wildfly/bin/
        owner: wildfly
        group: wildfly
        mode: "0700"
    - name: setting owner for wildfly
      file:
        path: /opt/wildfly
        owner: wildfly
        group: wildfly
        mode: "0755"
    - name: reloading systemd service
      systemd:
        daemon_reload: yes
#    - name: Configure SELinux
#      community.general.sefcontext:
#        target: "/opt/wildfly/bin(/.*)?"
#        ftype: "a"
#        setype: "bin_t"
#        state: present
#    - name:  Apply new SELinux file context to filesystem
#      ansible.builtin.command: restorecon -Rv /opt/wildfly/bin/
    - name: Configure SELinux
      shell:
        "{{ item }}"
      with_items: "{{ shell_commands }}"
#        "sudo semanage fcontext  -a -t bin_t  '/opt/wildfly/bin(/.*)?'"
#    - name: Apply new SELinux file context to filesystem
#      shell:
#        "sudo restorecon -Rv /opt/wildfly/bin/"
    - name : starting wildfly service
      service:
        name: wildfly
        state: started
        enabled: true


- name: Installing PostgreSQL
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    - packages:
        - postgresql
        - postgresql-server
        - postgresql-contrib
        - postgresql-libs
        - python3-psycopg2
  tasks:
    - name: installing packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
    - name: checking if PostgreSql is initialized
      stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data
    - name: Initialize PostgreSQL
      shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: Start and enable service
      service:
        name: postgresql
        state: started
        enabled: true


