---
- name: Installing jboss
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    - packages:
        - java-11-openjdk-devel
        - wget
        - curl
#    - wildfly_release_url:
#        - ansible-galaxy collection install middleware_automation.wildfly
#        - "https://github.com/wildfly/wildfly/releases/download/27.0.1.Final/wildfly-27.0.1.Final.tar.gz"
#          - "https://api.github.com/repos/wildfly/wildfly/releases/latest"
  tasks:
    - name: Downloading packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
    - name: wildfly url
      get_url:
        url: "https://github.com/wildfly/wildfly/releases/download/27.0.1.Final/wildfly-27.0.1.Final.tar.gz"
        dest: /home/centos
        mode: '0755'
#        with_items: "{{ wildfly_release_url }}"
    - name: unarchiving tar
      ansible.builtin.unarchive:
        src: "/home/centos/wildfly-27.0.1.Final.tar.gz"
        dest: /opt/wildfly
        remote_src: yes

