---
- name: Installing jboss
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    - packages:
        - java-11-openjdk-devel
        - wget
        - curl
    - wildfly_release_url: "https://api.github.com/repos/wildfly/wildfly/releases/latest"
  tasks:
    - name: Downloading packages
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
    - name: wildfly url
      get_url:
        url: "{{ wildfly_release_url }}"
        dest: ./repos/wildfly/wildfly/releases/latest

