---
- name: Installing jboss
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    - packages:
        - java-11-openjdk-devel
        - wget curl
        - wildfly_release_url: "https://api.github.com/repos/wildfly/wildfly/releases/latest|grep tag_name|cut -d '"' -f 4"
  tasks:
    - name: Downloading packages
      yum:
        name: "{{ packages }}"
        state: present
      get_url:
        url: "{{ wildfly_release_url }}"