---
- name: Install MySQL
  hosts: database_group
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: Installing package
      yum:
        name: epel-release
        state: present
    - name: Installing Repo
      shell: sudo rpm -Uvh http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
#      get_url:
#        url: "http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm"
#        dest: /etc/yum.repos.d/mysql-community-source.repo
      ignore_errors: yes
    - name: "Installing MySQL 5.7"
      package:
        name: mysql-community-server
        state: present
    - name: Start the MySQL service
      become: true
      service:
        name: mysqld
        state: started
        enabled: true