---
- name: Installing MySql
  hosts: database_group
  become: yes
  tasks:
    - name: Installing package
      yum:
        name: epel-release
        state: present

    - name: Installing Mysql Rpm
      get_url:
        url: "http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm"

#        dest: ./mysql80-community-release-el7-5.noarch.rpm
        dest: /etc/yum.repos.d/mysql-community.repo
    - name: Installing Mysql
      yum:
        name: mysql-community-server
        state: present
    - name: starting mysql service
      service:
        name: mysqld
        state: started
        enabled: true


















