---
- name: Installing MySql
  hosts: database_group
  become: yes
  tasks:
    - name: Installing packages
      get_url:
        url: "https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm"
    - name: adding mysql repositories
      package:
        name: mysql80-community-release-el7-3.noarch.rpm

    - name: installing mysql
      yum:
        name: mysql-server
        state: present
    - name: starting mysql
      service:
        name: mysql
        state: started
        enabled: true












