---
- name: shell execution
  hosts: database_group
  become: yes
  tasks:
    - name: copy
      copy:
        src: "create_ec2_instance.sh"
        dest: "create_ec2_instance.sh"
    - name: shell
      shell:
        "./create_ec2_instance.sh"

