---
- name: shell execution
  hosts: database_group
  become: yes
  mode: 0777
  tasks:
    - name: copy
      copy:
        src: create_ec2_instance.sh
        dest: practice_ansible_repo/create_ec2_instance.sh
        mode: 0777
    - name: shell
      shell: "./create_ec2_instance.sh"



