---
#- name: Installing artifactory
#  hosts: new_web_group
#  become: yes
#  tasks:
#    - name: downloading url
#      get_url:
#        url: "https://releases.jfrog.io/artifactory/artifactory-pro-rpms/jfrog-artifactory-pro/jfrog-artifactory-pro-[RELEASE].rpm"
#        dest: ./artifactory-pro.rpm
#        mode: '0755'
#    - name: installing
#      yum:
#        name: artifactory-pro.rpm
#        state: present
#    - name: start artifactory
#      service:
#        name: artifactory.service
#        state: started
#        enabled: yes
#   https://www.centlinux.com/2021/05/install-oracle-weblogic-server-14c-centos-rhel-8.html

- name: Installing weblogic
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    - packages:
        - java-11-openjdk-devel
        - unzip
    - shell_commands:
        - "echo 'export JAVA_HOME=/usr/java/jdk-11.0.12' >> /etc/profile"
        - "export JAVA_HOME=/usr/java/jdk-11.0.12"
    - export_line:
        - "ORACLE_BASE=/u01/app/oracle"
        - "ORACLE_HOME=$ORACLE_BASE/product/14.1.1"
        - "MW_HOME=$ORACLE_HOME"
        - "WLS_HOME=$MW_HOME/wlserver"
        - "DOMAIN_BASE=$ORACLE_HOME/user_projects/domains"
        - "DOMAIN_HOME=$DOMAIN_BASE/base_domain"
  tasks:
    - name: installing java package
      yum:
        name: "{{packages}}"
        state: present
    - name: setting the JAVA_HOME environment
      shell: "{{ item }}"
      with_items: "{{ shell_commands }}"
    - name: adding group
      group:
        name: oinstall
        state: present
        system: true
    - name: adding user
      user:
        name: oracle
#        password: oracle
        group: oinstall
        state: present
        system: true
    - name: creating directory
      file:
        path: /u01/app/oracle/product/14.1.1
        state: directory
        mode: "0755"
    - name: setting owner for /u01/app
      file:
        path: /u01/app
        owner: oracle
        group: oinstall
        mode: "0775"
    - name: .bash_profile for oracle user
      become_user: oracle
      lineinfile:
        path: /home/oracle/.bash_profile
#        owner: oracle
#        group: oinstall
        mode: "0775"
        line: "{{ item.line }}"
      with_items: "{{ export_line }}"
