---
#- name: test facts
#  hosts: localhost
#  become: yes
#  gather_facts: true
#  vars:
#    ansible_python_interpreter: /usr/bin/python3

---
- name: Installing jboss
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    - packages:
        - java-11-openjdk-devel
  tasks:
    - name: Downloading packages
      yum:
        name: "{{ packages }}"
        state: present