---
- name: test file
  hosts: localhost
  become: yes
  gather_facts: true
  tasks:
    - name: creating a file
      file:
        path: /home/centos/practice_ansible_repo/test_file1
        state: touch
    - name: adding a line
      lineinfile:
        path: /home/centos/practice_ansible_repo/test_file1
        state: present
        line:
          - "hello '\n' world '\n' hi"
